## What does import do 

import statement is used to bring in external modules or libraries into a program and allows you to use the functionality defined in these modules in your own code.

### What is Python

* Python is High Level, Dynamic type, interpretable, object oriented programming language.

* 1. High Level : it is easy to read, write and understand.


* 2. Dynamic Type: Means it with check the data type during the excution rather then before executing the code.

* 3. Interpretable: It will execute the code line by line.


* 4. Object Oriented Programming language: which associate with the concept such as object, class, method, inheritence, polmorphysam.
    * 1. Object: Are nothing but collection of data.
    * 2. Method: which are work on that data.
    * 3. Class : it is tamplete defining object and method.
    * 4. Inheritence: Ability of class to take the data from other class.
    * 5. abstraction : means hidding the unneccesary details such as data related info or process related info.
    * 6. Polmorphysam: Multi form means same method can be used in multi class.

.

self : Self is instance of class allow to access attribute and method inside the class.
    
__init__ : it is constructer method in python it will assing new object or attribute whenever new instace of class been created

.

Variable : use to assign the data with unique name:
        
        like name = 'Pranay' where name is variable
        
attribute: Value associate with the object:

    Example: person1 = parent('Name',age)
    
    person1 = object
    attribute = 'Name', age

Parameter : Parameters are the variable use inside the functions.
    
    as def square(a):
        here a is parameter
        
        
        

### In-build Data Type

1. Numeric Types:

* int: Integer type, e.g., 42.
* float: Floating-point type, e.g., 3.14.
* complex: Complex number type, e.g., 1 + 2j.

2. Sequence Types:

* str: String type, e.g., 'Hello, World!'.
* list: List type, e.g., [1, 2, 3].
* tuple: Tuple type, e.g., (1, 2, 3).

3. Set Types:

* set: Set type, e.g., {1, 2, 3}.

4. Mapping Type:

* dict: Dictionary type, e.g., {'key': 'value'}.

5. Boolean Type:

* bool: Boolean type, either True or False.

6. None Type:

* None: Represents the absence of a value or a null value.

### Numerice : int, float, complex

In [132]:
### int
a = '55'
result = int(a)
result

55

In [133]:
### float
a = '55'
result = float(a)
result

55.0

In [134]:
a = ['1','2','3','5','6']
a

b = []

for i in a:
    b.append(int(i))
print(b)

[1, 2, 3, 5, 6]


In [135]:
l = ['1',2,'3','4',4]
c = []
for i in l:
    if isinstance(i,(str)):
        c.append(int(i))
    else:
        c.append(i)
print(c)

[1, 2, 3, 4, 4]


In [136]:
### complex
a = 1 + 2j
a

(1+2j)

### Sequencial: list, tuple, Str

* list: is a mutable datatype means if you can make changes after arranged.
* Tuple: is immutable datatype

* list:
    1. It can store multiple datatype.
    2. We cannot perform aggregation on it.
    3. we can extent if needed.
    4. more amount of memory required.
    5. slower then array.

* Array:
    1. It can store only one datatype.
    2. we can perform aggregation on it.
    3. less memory required.
    4. faster than list.

### list

In [137]:
# list 
l = [1,2,3,4,5,6]
type(l)

list

In [138]:
## append : use to add only one element or value.
l.append(5)
l

[1, 2, 3, 4, 5, 6, 5]

In [139]:
l.append([5,6])
l

[1, 2, 3, 4, 5, 6, 5, [5, 6]]

In [140]:
## extend : use when we have to add multiple values.
l.extend([5,6,7])
l

In [141]:
## insert is use when we have to add value at specific point.
l.insert(0,10)
l

In [142]:
## remove
l.remove([5,6])
l

### In list pop remove last by default. In set it remove first

In [143]:
## pop : pop will remove the last element or value. If we specifiy any value then it will remove from that position of index.
l.pop(1)
l

In [144]:
## clear will remove everything.
l.clear()
l

In [145]:
### Swap the first and last number only.
l  = [12, 35, 9, 56, 24]

a = l[0]
l[0] = l[4]
l[4] = a

l

In [146]:
## Secound largest number in list
l= [4, 5, 1, 2, 9, 7, 10, 8]
c = []
for i in l:
    if i is not max(l):
        c.append(i)
        
max(c)

In [147]:
## Print range of positive and negative
p = []
n = []
for i in range(-5,8):
    if i >= 0:
        p.append(i)
    else:
        n.append(i)
print(len(p),'and',len(n))

In [148]:
### Droping the null tuple from list
l = [(), ('ram','15','8'), (), ('laxman', 'sita'), ('krishna', 'radha', '45'), (','),()]

for i in l:
    if len(i) != 0:
        print(i)

In [149]:
### Droping duplicates from list

l = [10, 20, 30, 20, 20, 30, 40, 50, -20, 60, 60, -20, -20]
unique = []
duplicates = []
for i in l:
    if i not in unique:
        unique.append(i)
    else:
        duplicates.append(i)
print(unique, ' & ', list(set(duplicates)))

In [150]:
### list to dict

l = ["Gfg", 3, "is", 8, "Best", 10, "for", 18, "Geeks", 33]
l

name = []
id = []
for i,j in enumerate(l):
    if i%2 == 0:
        name.append(j)
    else:
        id.append(j)

for i in range(5):
    result = {name[i] : id[i]}
    print(result)

In [151]:
## Python Program to print all Possible Combinations from the three Digits
l = [1,2,3]

for i in range(3):
    for j in range(3):
        for k in range(3):
#             if (i!=j and j!=k and i!=k):
            print(l[i], l[j], l[k]) 

In [9]:
### let me know what result is
l = [1,2,3,4,5,6,7]

for i in l:
    l.remove(i)
    
print(l)

[2, 4, 6]


In [45]:
## Bubble sort
a = [15,49,29,57,23,4]

for j in range(0,len(a)):
    for i in range(0,len(a)):
        if i == len(a) - 1:
            break

        elif a[i + 1] > a[i]:
            pass

        else:
            temp = a[i]
            a[i] = a[i+1]
            a[i+1] = temp

a

[4, 15, 23, 29, 49, 57]

### tuple : we can not perform add remove conditions.

In [152]:
l = [10, 10, 1, 2, 3, 4, 5, 6, 5, 5, [5, 6], 5, 6, 7, 5, 6, 7]
a = tuple(l)
a

In [153]:
b = list(a)
b[1]

In [154]:
## if you want value from specific index.
b[1:7]

In [155]:
b[:-1]

In [156]:
## if we want whole list in reverse form
b[::-1]

In [157]:
### Reverse tht string
s ="geeks quiz practice code"
s = s.split()
s = s[::-1]
s = ' '.join(s)
s

In [158]:
### python program to create a list of tuples from given list having number and its cube in each tuple

l = [1,2,3]
b = []
for i in l:
    a = (i,i**3)
    b.append(a)
print(b)

In [159]:
### Change each element of tuple

t = [(1, 3, 4), (2, 4, 6), (3, 8, 1)]
index1 = 0
value1 = 55

b = []
for i in t:
    new_list = list(i)
    new_list[index1] = value1
    new_tup = tuple(new_list)
    b.append(new_tup)
print(b)

In [160]:
#Multiply Adjacent elements
t = (1, 5, 7, 8, 7, 4, 8, 10) 
result = []
for i in range(0,len(t) - 1):
    s = t[i] * t[i+1]
    result.append(s)
tuple(result)

In [161]:
### Add the if it match first one.
l = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)] 
x= []
for i in l:
    if i[0] not in x:
        x.append(i[0])
        
res = []
for i in x:
    p = []
    p.append(i)
    
    for j in l:
        
        if i == j[0]:
            
            p.append(j[1])
    res.append(p)
res

### range

In [162]:
a = range(1,10)
a

In [163]:
a = range(1,10)
print(*a)

In [164]:
a = list(range(1,10,2))
a

### str

In [165]:
a = 'My name is Pranay, Pranay has done the graduation in ECE and after that Pranay join data science'
a

In [166]:
a='Name'
b='James'
c= a + ' is ' + b
c

In [19]:
a='Name'
b='James'
print(a,'is',b,sep=' ')


Name is James


In [20]:
a = 'Name is James'
x,y, *z = a
print(x)
print(y)
print(z)

N
a
['m', 'e', ' ', 'i', 's', ' ', 'J', 'a', 'm', 'e', 's']


In [22]:
a = 'Name is James'
x,y, *z, d = a
print(x)
print(y)
print(z)
print(d)

N
a
['m', 'e', ' ', 'i', 's', ' ', 'J', 'a', 'm', 'e']
s


In [168]:
a = 'My name is Pranay, Pranay has done the graduation in ECE and after that Pranay join data science'
a
a.upper()

In [169]:
a.lower()

In [170]:
### Capitalize
a.capitalize()
a

In [171]:
### I want to replace first 2 pranay name with vicky
a.replace('Pranay','Vicky',2)
a

In [172]:
### in -1 ,-2 it won't work.
a = 'My name is Pranay , Pranay has done the graduation in ECE and after that Pranay join data science'
a

In [173]:
a.replace('Pranay','Vicky',-1)

In [174]:
### I want to replace the space with **
a.replace(' ', '***')

In [175]:
## I want to split
a.split("***")
a = str(a)
a

In [176]:
b = a.split(' ')
b

In [177]:
for i in b:
    if "m" in i:
        print(i)
    elif "M" in i:
        print(i)
    

In [178]:
## if we have this list and we want to join
b

In [179]:
result = ' '.join(b)
result

In [180]:
### how to drop duplicate from str
print(result)

s = result.split(' ')

unique_s = set(s)

result = ' '.join(unique_s)

result 

In [181]:
string_list = ['My name is Pranay. Pranay has done the BE in ECE. Pranay is a good employee, and Pranay is going to be promoted.',
               'Another Pranay example. Pranay is skilled in Python programming. Pranay is also a quick learner.']

# Replace the first and third occurrences of 'Pranay' with 'Vicky' in each string
for i in range(len(string_list)):
    string_list[i] = string_list[i].replace('Pranay', 'Vicky', 2)
# Print the updated list of strings
for string in string_list:
    print(string)


### set : it is mutable datatype
* it is a ordered datatype
* it won't take the duplicate values.

* forzenset: immutable datatype

In [182]:
s = {1,2,3,4,5,6,67,99}
type(s)

In [183]:
l = list(s)
l

In [184]:
s = set(l)
s

In [185]:
set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}

set3 = set1.union(set2)
print(set3)

In [186]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.intersection(y)

print(z)


In [187]:
## To add into list
s.add(100)
s

In [188]:
### To add multiple values we have update
s.update([33,31,331])
s

In [189]:
### To remove
s.remove(331)
s

In [190]:
## Frozenset
fs = frozenset(s)
fs

In [191]:
### count the unique num with there duplicate count.
lis = [1,1,1,1,2,3,2,2,1,2,3,4,4,5]
s = set(lis)
s

results ={}
for i in s:
    result = {i: lis.count(i)}
    results.update(result)
    
results

In [10]:
### remove first from set
s = set([12, 10, 13, 15, 8, 9])
s
while s:
    s.pop()
    print(s)

{9, 10, 12, 13, 15}
{10, 12, 13, 15}
{12, 13, 15}
{13, 15}
{15}
set()


In [16]:
## Let me know the output
a = {True,0.0,"",0,False,1}
a

{'', 0.0, True}

In [61]:
a = {False,0.0,"",0,True,1,True}
a

{'', False, True}

### Dict

In [194]:
d = {'a':1, 'b':2, 'c':3}
d

In [195]:
e = {'d':5}
e

### To add dict we have only one keyword update

In [196]:
d.update(e)
d

In [197]:
import pandas as pd
df = pd.DataFrame(d,index = [1])
df

In [198]:
for i,j in df.items():
    df[i] = j + 5

In [199]:
d['ele'] = 9
d

In [200]:
d.keys()

In [201]:
d.values()

In [202]:
### we have delet key word in dict
d = {'a':1, 'b':2, 'c':3}

del d['c']

print(d)

In [203]:
del d

In [204]:
## How to sort dic
d = {'ravi': 10, 'rajnish': 9, 'sanjeev': 15, 'yash': 2, 'suraj': 32}

l = list(d)
l.sort()

s = {}
for i in l:
    res = {i : d[i]}
    s.update(res)
s

In [205]:
### for dictionary we use items with for loop.
d = {'ravi': [10,20,30], 'rajnish': [9], 'sanjeev': [15,3,3], 'yash': [2], 'suraj': [32]}

for i,j in d.items():
    if len(j) <= 1:
        pass
    else:
        print(j)


In [206]:
### Sumation of values:
d = {"‘a’": 100, "‘b’":200, "‘c’":300}

s = 0
for k,v in d.items():
    s = s + v
print(s)

### Boolen: True or Flase
* it bydefault give true unless list is empty or having zero values

In [207]:
a = 'Pranay'
b = 0
c = []
d = [1]

print(f'{a} : ', bool(a))
print(f'{b} : ', bool(b))
print(f'{c} : ', bool(c))
print(f'{d} : ', bool(d))

### None Datatype: pass

pass: it does not perform any operation or action. it provide the output as nothing.

we use it we don't want to perform any action on given condition.
It's just a way to satisfy the syntax requirements when a statement is needed but no action is desired.

### for and while loop
1. For loop: it is use for continously iterate the perticular statement until and unless condition is not being satisfied.
2. while: It will continously iterate over the perticular statement unless condition not become flase.

## This is called list comprehension converting one list to another.
List comprehension is a concise way to create lists in Python. It provides a more compact syntax for creating lists compared to using traditional loops. 


In [208]:
l = [i for i in range(1,10)]
l

In [209]:
## List Comprehension with Condition:
l = [i for i in range(1,10) if i%2 == 0]
l

In [210]:
# List Comprehension with Transformation:
words = ['apple', 'banana', 'cherry']
uppercase_words = [word.upper() for word in words if 'e' in word]
uppercase_words

In [211]:
## Create addition using this.
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
sum = 0

result = []
for i in l:
    sum = sum + i
    result.append(sum)
print(result)

In [212]:
### recursion: when function execute or call itself again and again.
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
mul = 1

result = []
for i in l:
    mul = mul * i
    result.append(mul)
print(result)

In [213]:
### Creating tables
for i in range(1,3):
    for j in range(1,11):
        print(f'{i} * {j} : {i*j}')
    print('*****'*10)

In [214]:
### check weather num is even or odd.
l = [1, 3, 6, 10, 15, 21, 28, 36, 45]
even = []
odd = []

for i in l:
    if i%2 ==0:
        even.append(i)
    else:
        odd.append(i)
print(even)
print(odd)

In [215]:
### Number is unique or not
l = [1, 3, 6, 10, 15,3, 21,128,4,44,4,6,36, 45]
unique = []
not_unique = []

for i in l:
    if i not in unique:
        unique.append(i)
    else:
        not_unique.append(i)
print(unique)
print(not_unique)

In [216]:
### split numeric and str
a =  [18,'pranay',21, 24,'ss',27,'mm',30, 33]

p = []
m = []

for i,j in enumerate(a):
    if isinstance(j,(int)):
        p.append(j)
        
    else:
        m.append(j)

print(p,m)

In [217]:
### Prime or not:
for i in range(10):
    for j in range(2,i):
        if i%2 ==0:
            print(f'{i}: Not a Prime Number')
            break
    else:
        print(f'{i}: Prime Num')
        
### If we remove break then it will give 4 as not prime and prime as well
### if we put else after if then it will give 0 time 2, 1 time 3, 2 times 4, 3 times 5 , 4 times 6 like wise result produce.

In [218]:
for i in range(6):
    for j in range(i+1):
        print(i, end = ' ')
    print()

In [219]:
for i in range(6):
    for j in range(i+1):
        print(j, end = ' ')
    print()

In [220]:
num = 0
for i in range(6):
    for j in range(i+1):
        print(num, end = ' ')
        num = num + 1
    print()

In [221]:
l = [18, 21, 24, 27, 30, 33] 
prev = 0
for i in l:
    s = prev + i
    prev = i
print(s)

In [222]:
#Leap Year (366 day present then its leap year.) (2000,2004,1980)

year = int(input('Enter Any Year You Want : '))
print('***'*12)

if ((year % 400 == 0)) or ((year % 100 != 0) & (year % 4 == 0)):
    
    print(f'This year {year} is a leap Year')
    print('***'*12)

else:     
    
    print(f'This year {year} is not a leap Year')
    print('***'*12)

Enter Any Year You Want : 34


In [223]:
#LCM: Least common multiple.()
def lcm(n1,n2):
    
    for i in range(1,max(n1,n2)):
        if n1%i == n2%i ==0:
            hcf = i
            
    result = (n1*n2) // hcf
    
    return result

lcm(88,99)

In [224]:
# Armstrong number
n = int(input('Enter 3 digit Num: '))

a = n % 10

r = n//10

b = r % 10

c = r // 10

print(a,b,c,sep = ' ')
if a**3 + b**3 + c**3 == n:
    print('It;s Armstrong Num')
else:
    print('It is not')

Enter 3 digit Num: 34


In [225]:
# narcissist number

n = int(input('Enter 3 digit Num: '))

a = n % 10

r = n//10

b = r % 10

c = r // 10

print(a,b,c,sep = ' ')
if a**4 + b**4 + c**4 == n:
    print('It;s narcisst Num')
else:
    print('It is not')

Enter 3 digit Num: 33


In [226]:
# The current population of a town is 10000. The population of the town is increasing at the rate
# of 10% per year. You have to write a program to find out the population at the end of each of the last 10
# years. For eg current population is 10000 so the output should be like this:


p=10000
for i in range(1,10):
 p=p-0.1*p
 print(round(p),end=" ")

In [227]:
a = 456
for i in reversed(str(a)):
    print(i)

In [228]:
### continew: It is use to bypass particular condition.
l = [18, 21, 24, 27, 30, 33] 
s = []
for i in l:
    if i in [21,22,23]:
        continue
    else:
        s.append(i)
s        

### while:

In [229]:
### how to sum the given number:
a = int(input('Enter Num:'))
sum = 0
while a!= 0:
    r = a % 10
    sum = sum + r
    a = a//10
print(sum)

Enter Num:33


In [230]:
## Guess game

correct = 'Pranay'
guess = 0
guess_count = 0
guess_lim = 3

while guess != correct:
    
    if guess_count > guess_lim:
        print('You loss the game.')
        break
    
    guess = input('Enter you guess : ')
    guess = guess.capitalize()
    guess_count +=1
    
    if guess == correct:
        print('You won the game, Congratulations!!')
    else:
        print(f'{guess_lim - guess_count} attempt left')

Enter you guess : 33
Enter you guess : 33
Enter you guess : 33
Enter you guess : 33


### Functions:
* Function as set of organized block of reusable code to perform specific task.

In [231]:
def fib(n): 
    a = 0
    b = 1
    
    result = []
    for i in range(n):
        c = a + b
        a = b
        b = c
        
        result.append(c)
    return result

fib(5)

In [232]:
def pele(name):
    rev = ''.join(reversed(name))
#     rev = name[::-1]
    if name == rev:
        return True
    else:
        return False

pele('naman')

In [233]:
def sumation(a,b,c):
    return a+b+c
n1 = [1,2,3,4,5]
n2 = [2,3,4,5,6]
n3 = [3,4,5,6,7]

result = map(sumation,n1,n2,n3)
list(result)

### lambda
* it is a nameless annonymous function use to perform small one time operation

In [234]:
a = lambda x : x**3
a(5)

In [235]:
sumation = lambda a,b,c: a+b+c
sumation(1,2,4)

In [236]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)
mytripler = myfunc(3)

print(mydoubler(11))
print(mytripler(11))

In [237]:
## only on lambda and i put brackets
a = [(lambda x: x+2)(i) for i in range(1,10) if i%2 == 0]
a

#### Use the lambda example as much as possible.

In [238]:
import pandas as pd

# Assuming df is your DataFrame with a column named 'id'
data = {'id': [1, 2, 3, 4, 5],
        'other_column': [10, 20, 30, 40, 50]}

df = pd.DataFrame(data)

# Use lambda function with apply to add 5 to the 'id' column
df['id'] = df['id'].apply(lambda x: x + 5)

# Print the modified DataFrame
print(df)


In [239]:
import pandas as pd

# Assuming df is your DataFrame with a column named 'name'
data = {'name': ['John', 'Alice', 'Bob', 'Charlie', 'David']}

df = pd.DataFrame(data)

# Use lambda function with apply to find the length of each name
df['name_length'] = df['name'].apply(lambda x: len(x))

# Print the modified DataFrame
print(df)


In [240]:
a = ['pranay','swati','priti']
res = []
for i in a:
    b = len(i)
    res.append(b)

d = {'Name' : a, 'Lenth' : res}
d

import pandas as pd
r = pd.DataFrame(d)
r['new'] = [1,2,3]

In [241]:
r

In [242]:
## Pass is null operator which does not perform any task and also it returns nothing.
## it is used to satisfy the syntex.

a = 1
b = 1
if a+b != 0:
    # TODO: Add code here
    pass
else:
    # Some other code
    print("Condition is false.")


### Try and Except : Use for exception handling. 


In [243]:
try:
    # Code that might raise an exception
    numerator = int(input("Enter the numerator: "))
    denominator = int(input("Enter the denominator: "))
    
    result = a+b

except ZeroDivisionError:
    # Handling the specific exception: division by zero
    print("Error: Division by zero is not allowed.")

except ValueError:
    # Handling the specific exception: invalid input (non-integer)
    print("Error: Please enter valid integers.")

except Exception as e:
    # Handling any other unexpected exceptions
    print(f"An unexpected error occurred: {e}")

else:
    # Code to be executed if no exception is raised
    print(f"The result of the division is: {result}")

finally:
    # Code to be executed regardless of whether an exception occurred or not
    print("This block will always be executed.")


Enter the numerator: 3
Enter the denominator: 33


### Iterator and Generator.

* iterator: use the iter keyword to print the element present inside the list.
    * Elements present inside the list know as iterables

* Generator : is use to create the iterator. To create generator we use the function with yield keyword.
    * it also save and return the local variable
    * use to create fast and compact code

In [244]:
# iterables
l = [1,2,3,4,4,5,6]

iterator = iter(l)
next(iterator)

In [245]:
next(iterator)

In [246]:
## Generator
def square(n):
    for i in range(n):
        yield i**4
        
for j in square(4):
    print(j)

In [247]:
a = square(n)
next(a)

In [248]:
next(a)

### Decorator:
* allows a user to add new functionality to an existing object without modifying its structure.

In [249]:
### Decorator:
def primary_class(fun):
    def sub_class():
        print('Hi, My name is Pranay')
        fun()
        print('I am currently working as Data Scientist in CG')
    return sub_class


In [250]:
@primary_class
def graduation():
    print('I have done the data science')
    
graduation()

### Class

In [251]:
# single
class Parent():
    def Parent(self):
        print('I am Parent')
    
class child(Parent):
    def child(self):
        print('I am child')

a = Parent()
b = child()

b.Parent()
b.child()

In [252]:
# multi
class Parent1():
    def Dad(self):
        print('I am Dad')
    
class Parent2():
    def Mom(self):
        print('I am Mom')
    
class child(Parent1,Parent2):
    def child(self):
        print('I am child')

a = Parent1()
c = Parent2()
b = child()

b.Dad()
b.Mom()
b.child()

In [253]:
# multi
class GrandFather():
    def GrandFather(self):
        print('I am GrandFather')
    
class Father(GrandFather):
    def Father(self):
        print('I am Father')
    
class son(Father):
    def child(self):
        print('I am child')

a = GrandFather()
c = Father()
b = son()

b.GrandFather()
b.Father()
b.child()

In [254]:
# Hirarcy
class Parent():
    def Parent(self):
        print('I am Parent')
    
class Child1(Parent):
    def Child1(self):
        print('I am Child1')
    
class Child2(Parent):
    def Child2(self):
        print('I am Child2')

a = Parent()
c = Child1()
b = Child2()

b.Parent()
c.Parent()

In [255]:
class animal():
    def speak(self):
        pass

class Bird():
    def speak(self):
        return print('chi chi')
        
class Dog():
    def speak(self):
        return print('Bho Bho')

class Cat():
    def speak(self):
        return print('Meow Meow')


a = animal()
a.speak()

b = Bird()
b.speak()

In [256]:
class Shape:
    def area(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return 3.14 * self.radius ** 2

class Square(Shape):
    def __init__(self, side_length):
        self.side_length = side_length

    def area(self):
        return self.side_length ** 2

# Function that works with objects of the base class Shape
def print_area(shape_obj):
    print(f"Area: {shape_obj.area()}")

# Example usage of polymorphism
circle = Circle(5)
square = Square(4)

print_area(circle)  # Output: Area: 78.5
print_area(square)  # Output: Area: 16


### Pandas

In [257]:
import pandas as pd

l = [1,2,3,4,5,6,6]

df = pd.DataFrame(l, columns = ['a'])
df

In [258]:
d = {'a' : [1,2,3], 'b': [1,22,33],'c': [1,4,3]}
df = pd.DataFrame(d,index = [1,2,3])
df

In [259]:
s = pd.Series([1,2,3,4,5,6,67])
df = pd.DataFrame(s)
df

### Numpy

In [2]:
import numpy as np

a = np.array([1,2,3,3,4,5])
print(a) 
print()
print('*****'*10)

a = np.array([[1,2],[2,3]])
print(a) 
print()
print('*****'*10)

a = np.arange(1,10,3)
print(a) 
print()
print('*****'*10)

a = np.zeros((3,5))
print(a) 
print()
print('*****'*10)

a = np.ones((3,5))
print(a) 
print()
print('*****'*10)


[1 2 3 3 4 5]

**************************************************
[[1 2]
 [2 3]]

**************************************************
[1 4 7]

**************************************************
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

**************************************************
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

**************************************************


In [3]:
l = list(range(1,7))

result = np.array(l).reshape(2,3)
result

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
l = list(range(1,7))

result = np.array(l)
result

array([1, 2, 3, 4, 5, 6])

In [262]:
### AWS Codes: Take the data from s3 and put back


# import boto3

# # Set your AWS credentials
# aws_access_key_id = 'YOUR_ACCESS_KEY_ID'
# aws_secret_access_key = 'YOUR_SECRET_ACCESS_KEY'
# aws_region = 'YOUR_AWS_REGION'

# # Set the name of your S3 bucket and the key (path) of the file
# bucket_name = 'your-bucket-name'
# file_key = 'path/to/your/file.txt'

# # Create an S3 client
# s3 = boto3.client('s3', aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key, region_name=aws_region)

# # Download the file from S3
# try:
#     response = s3.get_object(Bucket=bucket_name, Key=file_key)
#     content = response['Body'].read().decode('utf-8')
#     print(content)
# except Exception as e:
#     print(f"An error occurred: {e}")



# import boto3

# # Set your AWS credentials
# aws_access_key_id = 'YOUR_ACCESS_KEY_ID'
# aws_secret_access_key = 'YOUR_SECRET_ACCESS_KEY'
# aws_region = 'YOUR_AWS_REGION'

# # Set the name of your S3 bucket and the key (path) where you want to upload the file
# bucket_name = 'your-bucket-name'
# file_key = 'path/to/your/uploaded/file.txt'

# # Content to be uploaded
# content_to_upload = "This is the content to upload to S3."

# # Create an S3 client
# s3 = boto3.client('s3', aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key, region_name=aws_region)

# # Upload the file to S3
# try:
#     s3.put_object(Bucket=bucket_name, Key=file_key, Body=content_to_upload.encode('utf-8'))
#     print(f"File uploaded to S3: s3://{bucket_name}/{file_key}")
# except Exception as e:
#     print(f"An error occurred: {e}")




## 