In [6]:
print(*range(1,10,2))

1 3 5 7 9


In [5]:
print(list(range(1, 10,2)))

[1, 3, 5, 7, 9]


In [2]:
s = 'My name Pranay. Pranay has done the Data science and Pranay is from pune'
s.replace('Pranay','Vicky',2)

'My name Vicky. Vicky has done the Data science and Pranay is from pune'

In [2]:
num1 = [i for i in range(6)]
num2 = [i for i in range(6,12)]
num3 = [i for i in range(12,18)]

def sum(a,b,c):
    return a+b+c

result = map(sum,num1,num2,num3)
print(list(result))

[18, 21, 24, 27, 30, 33]


In [2]:
a =  [18,'pranay',21, 24,'ss',27,'mm',30, 33]

for i in a:
    
    if isinstance(i,(str)):
        print(i)

pranay
ss
mm


In [8]:
a =  [18,'pranay',21, 24,'ss',27,'mm',30, 33]

p = []
m = []

for i,j in enumerate(a):
    if i%2 == 0:
        p.append(j)
        
    else:
        m.append(j)

print(p,m)

[18, 21, 'ss', 'mm', 33] ['pranay', 24, 27, 30]


In [19]:
n = 0
for i in range(1,6):
    for j in range(1,i+1):
        print(n, end = ' ')
        n = n + 1
    print()

0 
1 2 
3 4 5 
6 7 8 9 
10 11 12 13 14 


In [29]:
n = 0
for i in range(0,6):
    print(f'{n}'* i )
    n = n+1


1
22
333
4444
55555


In [12]:
num = 0
for i in range(1,6):
    for j in range(1,i+1):
        print(j, end = ' ')
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [8]:
num = 0
for i in range(1,6):
    for j in range(1,i+1):
        print(num, end = ' ')
        num = num + 1
    print()

0 
1 2 
3 4 5 
6 7 8 9 
10 11 12 13 14 


In [8]:
def fib(n):
    
    a = 0
    b = 1
    
    for i in range(n):
        
        c = a + b
        a = b
        b = c
        
        print(c)
        
fib(7)

1
2
3
5
8
13
21


In [41]:
def pele(name):
    
    rev = ''.join(reversed(name))
    
    if name == rev:
        return True
    else:
        return False
    
pele('naman')

True

In [50]:
num = int(input('Enter Num: '))
result = 0

while num != 0:
    
    rem = num % 10 
    
    result = result + rem
    
    num = num//10
    
print(result)

Enter Num: 333
9


In [54]:
#Write a python program to search a given number from a list
a = [i for i in range(1,11)]

b = int(input('Enter num: '))

for i in a:
    
    if b == i:
        print('True')
        break
        
else:
    print('False')
        
    

Enter num: 99
False


In [57]:
prev = 0
for i in range(1,11):
    
    sum = i + prev
    
    prev = i

    print(sum)

1
3
5
7
9
11
13
15
17
19


In [46]:
#Even odd
l = ['Depu', 'Nitin', 'Priti', 'Pooja','jojo']
even = []
odd = []

for i,j in enumerate(l):
    if i%2 == 0:
        even.append(j)
    else:
        odd.append(j)
    
print('Even:',even)        
print('Odd:',odd)

Even: ['Depu', 'Priti', 'jojo']
Odd: ['Nitin', 'Pooja']


In [49]:
#Add one by on in list:
l = [i for i in range(1,8)]
sum = 0

for i in l:
    sum = sum + i
    print(sum)    

1
3
6
10
15
21
28


According to the definition of prime numbers, any whole number which has only 2 factors is known as a prime number.

In [3]:
#Task 2 Prime num
for i in range(1,10):
    
    for m in range(2,i):
        
        if i%m == 0:
            print(f'{i} is not prime num')
            break
            
    else: 
        print(f'{i} is prime num')

1 is prime num
2 is prime num
3 is prime num
4 is not prime num
5 is prime num
6 is not prime num
7 is prime num
8 is not prime num
9 is not prime num


In [2]:
#Divide unique and duplicate values.
list = [1,2,4,2,3,4,51,2,5,5,2,3,4]

unique  = []
duplicate = []


for i in list:
    
    if i not in unique:
        unique.append(i)
        
    else:
        duplicate.append(i)
    
    
print(f'Unique values : {unique}  ')
print(f'duplicate values : {duplicate}  ')

Unique values : [1, 2, 4, 3, 51, 5]  
duplicate values : [2, 4, 2, 5, 2, 3, 4]  


# Factorial is a part of recursion: which excute or call itself one or more time.

In [14]:
#Multiple (factorial)
i = int(input('Enter Your value : '))
Mult = 1

for x in range(1,i + 1):
    Mult = Mult * x
    
print(Mult)

Enter Your value : 7
5040


In [18]:
#Creating guessing game
correct = 7
Guess = 0
Guesscount = 0
Guesslimit = 3
print("Enter Any Number Between 0 to 10 ")


while(Guess != correct):
    
    if Guesscount >= Guesslimit:
        
        print('Your Run Out of Guess')
        print('**'*15)
        
        print('You Loss the Game (:')
        print('**'*15)
        
        break
    
    
    Guess = int(input('Enter Your Guess : '))
    Guesscount += 1
    
    if Guess == correct:
        
        print('***'*40)
        print('You have Correctly Guess the Number :)')
        print('***'*40)
        
    else:
        
        print('**'*15)
        print('**'*15)
        print(f'Only {3 - Guesscount} attempts are remain.')
        print('**'*15)
        print('**'*15)
    

Enter Any Number Between 0 to 10 
Enter Your Guess : 7
************************************************************************************************************************
You have Correctly Guess the Number :)
************************************************************************************************************************


In [76]:
#Table
for i in range(1,2):
    
    for j in range (1,11):
        
        print(f'{i} * {j} : {i*j}')

1 * 1 : 1
1 * 2 : 2
1 * 3 : 3
1 * 4 : 4
1 * 5 : 5
1 * 6 : 6
1 * 7 : 7
1 * 8 : 8
1 * 9 : 9
1 * 10 : 10


In [1]:
#Vowels
import string

a_z = list(string.ascii_lowercase)
vowels = ['a','e','i','o','u']
new = []

for i in a_z:
    
    if i not in vowels:
        
        new.append(i)
        
print(new)
    
    

['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z']


In [2]:
#Even Odd
i = int(input('Enter Your Number'))

if i%2 == 0:
    
    print(f'{i} is a Even Number')
    
else:
    
    print(f'{i} is a Odd Number')

Enter Your Number7
7 is a Odd Number


In [3]:
# User define addition.

first = int(input('Enter Your first Number : '))
sec = int(input('Enter Your sec Number : '))
sum = 0

for i in range (first,sec + 1):
    
    sum = sum + i

print(sum)    


Enter Your first Number : 7
Enter Your sec Number : 3
0


In [4]:
myList = [1,2,'t',22,34,'p',2]

In [107]:
l2 = []

for i in myList:
    if isinstance(i,(int)):
        l2.append(i)
        
print(l2)   

for i in l2:
    
    for m in range(2,i):
        
        if i%m == 0:
            print(f'{i} Its not a prime Number')
            
            
            if i%2 == 0:
                print(f'{i} Its Even Number')
                print('****'*9)
                break
            
            else:
                print(f'{i} Its Odd Number')
                print('****'*9)
                break
            
    
    else:
        print(f'{i} Its a prime Number')
        
        if i%2 == 0:
            print(f'{i} Its Even Number')
            print('****'*9)
        
    
        else:
            print(f'{i} Its Odd Number')
            print('****'*9)
    
    

0 Its a prime Number
0 Its Even Number
************************************
1 Its a prime Number
1 Its Odd Number
************************************
2 Its a prime Number
2 Its Even Number
************************************
3 Its a prime Number
3 Its Odd Number
************************************
4 Its not a prime Number
4 Its Even Number
************************************
5 Its a prime Number
5 Its Odd Number
************************************
6 Its not a prime Number
6 Its Even Number
************************************
7 Its a prime Number
7 Its Odd Number
************************************
8 Its not a prime Number
8 Its Even Number
************************************
9 Its not a prime Number
9 Its Odd Number
************************************
10 Its not a prime Number
10 Its Even Number
************************************
11 Its a prime Number
11 Its Odd Number
************************************
12 Its not a prime Number
12 Its Even Number
*************************

In [110]:
for i in range(8):
    print('*'* i)
    


*
**
***
****
*****
******
*******


In [4]:
n = 8
for i in range(n):
    print('*'*n)
    n = n-1

********
*******
******
*****
****
***
**
*


In [114]:
n = int(input())

for i in range(n):
    
    print('*'*n)
    
    n = n - 1
    

9
*********
********
*******
******
*****
****
***
**
*


In [8]:
#Addition of given phone Number.
number = int(input('Enter Your Number : '))
sum = 0

while number != 0 :
    
    rem = number % 10
    
    sum = sum + rem
    
    number = number//10
    
print(sum)    

Enter Your Number : 8765
26


0

In [4]:
#Leap Year (366 day present then its leap year.) (2000,2004,1980)

year = int(input('Enter Any Year You Want : '))
print('***'*12)

if ((year % 400 == 0)) or ((year % 100 != 0) & (year % 4 == 0)):
    
    print(f'This year {year} is a leap Year')
    print('***'*12)

else:     
    
    print(f'This year {year} is not a leap Year')
    print('***'*12)

Enter Any Year You Want : 1900
************************************
This year 1900 is not a leap Year
************************************


In [8]:
#LCM: Least common multiple.()

In [27]:
def lcm(n1,n2):
    
    for i in range(1,max(n1,n2)):
        if n1%i == n2%i ==0:
            hcf = i
            
    result = (n1*n2) // hcf
    
    return result

lcm(88,99)

792

In [4]:
#take 3 input and see which one is highest.
a = int(input("Enter Num: "))
b = int(input("Enter Num: "))
c = int(input("Enter Num: "))

if(a > b) and (a > c):
    
    print(f'{a} is highest')
    
elif(b > a) and (b > c):
    
    print(f'{b} is highest')

else:
    print(f'{c} is highest')

Enter Num: 1
Enter Num: 3
Enter Num: 2
3 is highest


In [1]:
# Mutable: list, set
# Immutable : Tuple,frozen set

#Ordered : set,frozenset
#Unordered : List,tuple,dictionary

#set won't take duplicate values.

In [18]:
# Armstrong number
n = int(input('Enter 3 digit Num: '))

a = n % 10

r = n//10

b = r % 10

c = r // 10

print(a,b,c,sep = ' ')
if a**3 + b**3 + c**3 == n:
    print('It;s Armstrong Num')
else:
    print('It is not')

Enter 3 digit Num: 371
1 7 3
It;s Armstrong Num


In [19]:
# narcissist number

n = int(input('Enter 3 digit Num: '))

a = n % 10

r = n//10

b = r % 10

c = r // 10

print(a,b,c,sep = ' ')
if a**4 + b**4 + c**4 == n:
    print('It;s narcisst Num')
else:
    print('It is not')

Enter 3 digit Num: 371
1 7 3
It is not


In [7]:
# Print all factors of a given number provided by the user

n = int(input('Enter Any No: '))

for i in range(1,n+1):
    if n%i == 0:
        print(i)
    

Enter Any No: 8
1
2
4
8


In [10]:
# # Write all content of a given file into a new file by skipping line number 5

# with open('File name','r') as fr:
#     lines = fr.readlines()

# with open('file exp name','w') as fw:
#     count = 0
    
#     for line in range(lines):
        
#         if count == 4:
#             count +=1
#             continue
        
#         else:
#             fw.write(line)
#         count +=1

In [12]:
# # Check file is empty or not Write a program to check if the given file is empty or not

# import os

# size = os.stat('').st_size

# if size == 0:
#     print('file empty')

# else:
#     print('its not')

In [15]:
# Add privious num
# Print the sum of the current number and the previous number Write a program to iterate the first
# 10 numbers and in each iteration, print the sum of the current and previous number.
# Expected result: 0,1,3,5,7,9,11,13,15,17

prev_num = 0
l = []

for i in range(1,11):
    
    x = i + prev_num
    prev_num = i
    
    l.append(x)
print(l)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [10]:
#Write a python program to search a given number from a list

l = [1,11,28,33,98,47,5]

num = int(input('enter num: '))

for i in l:
    
    if i == num:
        print('yes')
        break
else:
    print('no')
    

enter num: 6
no


In [33]:
# The current population of a town is 10000. The population of the town is increasing at the rate
# of 10% per year. You have to write a program to find out the population at the end of each of the last 10
# years. For eg current population is 10000 so the output should be like this:


p=10000
for i in range(1,10):
 p=p-0.1*p
 print(round(p),end=" ")
    

9000 8100 7290 6561 5905 5314 4783 4305 3874 

In [19]:
#Greatest Common Divisor
def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

# Example usage:
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

result = gcd(num1, num2)
print(f"The GCD of {num1} and {num2} is: {result}")


Enter the first number: 5
Enter the second number: 8
The GCD of 5 and 8 is: 1


In [10]:
name = 'Swati'

print(' '.join(reversed(name)))

i t a w S


In [13]:
num=int(input('enter the number:'))
for i in reversed(str(num)):
    print('reversr number:',i)

enter the number:786
reversr number: 6
reversr number: 8
reversr number: 7


In [15]:
num = 0
sum = 0
while num!=10:
    
    sum = sum + num
    num +=1 
    print(sum)

0
1
3
6
10
15
21
28
36
45


In [25]:
a='Name'
b='James'
print(a,'is',b,sep=' ')

Name is James


In [39]:
with open('CMPs.json','r') as fp:
    x = fp.readline()
    print(x)

I love python22


In [38]:
with open('CMPs.json','w') as fp:
    x = fp.write('I love python22')
    print(x)

15


In [40]:
def find_greatest_number(numbers):
    if not numbers:
        return None  # Return None for an empty list

    greatest = numbers[0]  # Assume the first number is the greatest

    for num in numbers:
        if num > greatest:
            greatest = num

    return greatest

# Example list
number_list = [12, 45, 9, 101, 24, 6]

# Call the function and print the result
print("The greatest number in the list is:", find_greatest_number(number_list))


The greatest number in the list is: 101


In [41]:
def find_greatest_number(numbers):
    return max(numbers)

# Example list
number_list = [12, 45, 9, 101, 24, 6]

# Call the function and print the result
print("The greatest number in the list is:", find_greatest_number(number_list))


The greatest number in the list is: 101


In [43]:
# import boto3

# # Set your AWS credentials
# aws_access_key_id = 'YOUR_ACCESS_KEY_ID'
# aws_secret_access_key = 'YOUR_SECRET_ACCESS_KEY'
# aws_region = 'YOUR_AWS_REGION'

# # Set the name of your S3 bucket and the key (path) of the file
# bucket_name = 'your-bucket-name'
# file_key = 'path/to/your/file.txt'

# # Create an S3 client
# s3 = boto3.client('s3', aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key, region_name=aws_region)

# # Download the file from S3
# try:
#     response = s3.get_object(Bucket=bucket_name, Key=file_key)
#     content = response['Body'].read().decode('utf-8')
#     print(content)
# except Exception as e:
#     print(f"An error occurred: {e}")


In [44]:
# import boto3

# # Set your AWS credentials
# aws_access_key_id = 'YOUR_ACCESS_KEY_ID'
# aws_secret_access_key = 'YOUR_SECRET_ACCESS_KEY'
# aws_region = 'YOUR_AWS_REGION'

# # Set the name of your S3 bucket and the key (path) where you want to upload the file
# bucket_name = 'your-bucket-name'
# file_key = 'path/to/your/uploaded/file.txt'

# # Content to be uploaded
# content_to_upload = "This is the content to upload to S3."

# # Create an S3 client
# s3 = boto3.client('s3', aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key, region_name=aws_region)

# # Upload the file to S3
# try:
#     s3.put_object(Bucket=bucket_name, Key=file_key, Body=content_to_upload.encode('utf-8'))
#     print(f"File uploaded to S3: s3://{bucket_name}/{file_key}")
# except Exception as e:
#     print(f"An error occurred: {e}")


s3 = boto3.client(s,k,re)

try:
    response = s3.get_object(b,f)
    content = r['Body'].read().decode('udf-8')
    
    s3.put_object(b,f,Body = content_to_upload.encode('udf-8'))

what is a function: In Python, a function is a block of organized, reusable code that performs a specific task.

Lambda: It is a name less anonymus function use to perform small and onetime operations.

In [46]:
import numpy as np

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [47]:
 np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [49]:
np.arange(1,5)

array([1, 2, 3, 4])

In [50]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### list comprehansion: converting one list to another.
    

In [54]:
list = [i for i in range(100)]
print(list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
